### ISSUE TITLE
Real data ? 

### ISSUE THREAD

**Issue by yqueau** [hiroaki-santo/light-structure-from-pin-motion#2]
Dear Hiroaki Santo, 

Would it be possible to have access to some real data, e.g. the ones used in the IJCV paper ? 

Thanks in advance, 
Yvain Queau

**Comment by hiroaki-santo** [comment]
Dear Yvain Queau,
Thank you for your request.
I will prepare some data. Please wait a few more days...

Thank you, 
Hiroaki

**Comment by hiroaki-santo** [comment]
Hi, 
I have uploaded sample data from our real-world experiments.
https://drive.google.com/file/d/1A8N5Q7Ljvpq2jpXVqp-yrFn7FaPkCSsj/

Best,
Hiroaki
