### ISSUE TITLE
Shadow tracking fails for unstructured data 

### ISSUE THREAD

**Issue by yqueau** [hiroaki-santo/light-structure-from-pin-motion#3]
Dear Hiroaki, 

Thank you again for sharing this very nice piece of work !

We are however facing a rather important issue. It seems that the provided implementation is limited to structured data, with limited motion between frames (e.g., a video input), as the shadow tracker on frame i uses info from frame i-1 (utils.tracking, line 277 in utils.py). 

This was clearly aknowledged in the ECCV18 paper ("One limitation of our method is that it requires the camera to be able to capture sequential images (i.e., a video) for tracking the shadows to solve the shadow correspondence problem."). However, this limitation was supposed to be overcome in the IJCV one ("If the input is a video for example, then we can track shadows over consecutive frames. However, it is clearly desirable to also be able to handle unstructured input just like regular SfM"), by relying on branch and bound. 

Is it possible to get access to the updated shadow tracker, so that we can use it on our unstructured data ? 

Thank you in advance, 
Yvain Queau

**Comment by hiroaki-santo** [comment]
Hi Yvain,
I appreciate your patience.
The new shadow correspondences algorithm is now implemented in `utils.shadow_correspondence()`.

Best,
Hiroaki
